### ISSUE TITLE
compilation errors

### ISSUE THREAD

**Issue by jflann** [memo33/scdbpf#1] opened 2022-07-03 20:41 UTC
scdbpf doesn't compile with sbt console

```
PS D:\GitHub\scdbpf> sbt console
[info] welcome to sbt 1.6.2 (Oracle Corporation Java 1.8.0_333)
[info] loading project definition from D:\GitHub\scdbpf\project
[info] loading settings for project scdbpf from build.sbt ...
[info] set current project to scdbpf (in build file:/D:/GitHub/scdbpf/)
[info] compiling 21 Scala sources and 1 Java source to D:\GitHub\scdbpf\target\scala-2.11\classes ...
[error] D:\GitHub\scdbpf\src\main\scala\scdbpf\Sc4Path.scala:156:76: value iterator is not a member of Iterator[String]
[error]       comment.toList flatMap (s => JavaConversions.asScalaIterator(s.lines.iterator)) map (_.trim) map
[error]                                                                            ^
[error] D:\GitHub\scdbpf\src\main\scala\scdbpf\internal\Sc4PathParser.scala:113:62: value iterator is not a member of Iterator[String]
[error]     val lines = JavaConversions.asScalaIterator(s.trim.lines.iterator).toSeq
[error]                                                              ^
[warn] D:\GitHub\scdbpf\src\main\scala\scdbpf\property.scala:140:26: abstract type A in type pattern scdbpf.DbpfProperty.ValueType.Numerical[A] is unchecked since it is eliminated by erasure
[warn]       case vt: ValueType.Numerical[A] => new SingleImpl(vt, value)
[warn]                          ^
[warn] one warning found
[error] two errors found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 6 s, completed Jul 3, 2022 3:35:41 PM
```

**Comment by memo33** [comment] 2022-07-04 18:47
This is already fixed on the current master branch by 5f161f707634d2b96a54ed36c19e67ec00da6e5c. Let me know if I should create a release bundle.

**Comment by jflann** [comment] 2022-07-04 19:45
Please forgive me if my ignorance is showing here, or if I am going about
this the wrong way - but my fork of scdbpf from which I am trying to use
the tools is even with the upstream/master and yet there are still
compilation errors.  You mentioned a release bundle - is that the key to
incorporating the latest changes?  Apologies for my lack of knowledge on
software development generally.

Thanks, flann

**Comment by memo33** [comment] 2022-07-04 21:53
No problem at all. It is my mistake – I did not read the error message carefully enough. I now see what the problem is. It should should go away if you update your Java installation to at least Java 11. I have tested it with Java 18. I am going to find a backward compatible fix tomorrow or in the coming days.

Alternatively, for the time being, you can also try to revert the changes to `Sc4Path.scala` and `Sc4PathParser.scala` from the commit linked to above and see if that works.

Whether a release is needed depends on what exactly you are planning to do. If you are using the files in this repository directly, it is not needed. But if you use this library as a dependency from inside another repository like `metarules` or `Network-Addon-Mod` and encounter this issue, a new release is needed as those repositories set the version of `scdbpf` to the release version 0.1.7 in their `build.sbt` files. In case you want to make changes and share them between the repositories to test them locally, you can also create a temporary [SNAPSHOT release](https://www.scala-sbt.org/1.x/docs/Publishing.html#Publishing+locally) for use on your computer.

**Comment by jflann** [comment] 2022-07-04 23:32
Thanks for the info.  I went ahead installed Java 18.  The project then successfully compiled.  However, there seems to be further compatibility issues.  Following the example in the docs:

```
scala> val dbpf = DbpfFile.read(new File("three_level_rhwC_L2.dat"))
java.lang.NumberFormatException: Not a version: 18
        at scala.util.PropertiesTrait$class.parts$1(Properties.scala:184)
        at scala.util.PropertiesTrait$class.isJavaAtLeast(Properties.scala:188)
        at scala.util.Properties$.isJavaAtLeast(Properties.scala:17)
        at scala.tools.nsc.util.StackTracing$class.stackTracePrefixString(StackTracing.scala:31)
        at scala.tools.nsc.util.package$StackTraceOps$.stackTracePrefixString$extension(package.scala:99)
        at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.bindError(IMain.scala:760)
        at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1048)
        at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:638)
        at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:637)
        at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
        at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
        at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:637)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:569)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:565)
        at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:807)
        at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:681)
        at scala.tools.nsc.interpreter.ILoop.processLine(ILoop.scala:395)
        at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:415)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:923)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:909)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:909)
        at scala.reflect.internal.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:97)
        at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:909)
        at xsbt.ConsoleBridge.run(ConsoleBridge.scala:75)
        at sbt.internal.inc.AnalyzingCompiler.console(AnalyzingCompiler.scala:208)
        at sbt.Console.console0$1(Console.scala:64)
        at sbt.Console.$anonfun$apply$5(Console.scala:74)
        at sbt.Run$.executeSuccess(Run.scala:186)
        at sbt.Console.$anonfun$apply$4(Console.scala:74)
        at sbt.internal.util.Terminal.withRawInput(Terminal.scala:145)
        at sbt.internal.util.Terminal.withRawInput$(Terminal.scala:143)
        at sbt.internal.util.Terminal$ProxyTerminal$.withRawInput(Terminal.scala:384)
        at sbt.Console.$anonfun$apply$3(Console.scala:74)
        at sbt.internal.util.Terminal$TerminalImpl.withRawOutput(Terminal.scala:975)
        at sbt.internal.util.Terminal$ProxyTerminal$.withRawOutput(Terminal.scala:423)
        at sbt.Console.apply(Console.scala:71)
        at sbt.Console.apply(Console.scala:49)
        at sbt.Console.apply(Console.scala:41)
        at sbt.Defaults$.$anonfun$consoleTask$1(Defaults.scala:2232)
        at sbt.Defaults$.$anonfun$consoleTask$1$adapted(Defaults.scala:2218)
        at scala.Function1.$anonfun$compose$1(Function1.scala:49)
        at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
        at sbt.std.Transform$$anon$4.work(Transform.scala:68)
        at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
        at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
        at sbt.Execute.work(Execute.scala:291)
        at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
        at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

Java 11 also compiles but produces the same `java.lang.NumberFormatException: Not a version: 11`

Edit:  I am successfully using the tools now after specifying `scalaVersion := "2.11.12"` in build.sbt

**Closed as completed** 2022-07-05 20:15 UTC

**Comment by memo33** [comment] 2022-07-05 20:16
Thanks for reporting that. This is now fixed.
